"""
Markdown report generator + unknown-companies CSV export.

Report structure (v1.1):
  1. Header + run summary
  2. New UK Jobs (first_seen > last run AND is_uk_role)
  3. Top Matches — UK Only (score >= 3 AND is_uk_role)
  4. Summary counts
"""

from __future__ import annotations

import csv
import logging
from pathlib import Path

from src.core.models import Job, RunRecord
from src.core.utils import is_uk_role

logger = logging.getLogger(__name__)


def generate_report(
    *,
    run: RunRecord,
    new_jobs: list[Job],
    all_jobs: list[Job],
    unknown_companies: list[dict],
    output_path: str | Path,
) -> str:
    """
    Generate a Markdown report and write it to *output_path*.

    Args:
        new_jobs: Jobs whose first_seen > previous run time (already scored).
        all_jobs: Every job fetched this run (already scored).
        unknown_companies: Company rows where ATS was not resolved.
        output_path: Where to write report.md.

    Returns the report content as a string.
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # ── Filter to UK ────────────────────────────────────────────────────
    new_uk = [j for j in new_jobs if is_uk_role(j.location)]
    new_uk.sort(key=lambda j: (j.company, j.title))

    top_uk = sorted(
        [j for j in all_jobs if j.score >= 3 and is_uk_role(j.location)],
        key=lambda j: j.score,
        reverse=True,
    )

    total_uk = sum(1 for j in all_jobs if is_uk_role(j.location))

    lines: list[str] = []

    # ── Header ──────────────────────────────────────────────────────────
    lines.append("# Job Aggregation Report")
    lines.append("")
    lines.append(f"**Run ID:** `{run.run_id}`")
    lines.append(f"**Timestamp:** {run.run_time}")
    lines.append(f"**Companies processed:** {run.companies_processed}")
    lines.append(f"**Total jobs found:** {run.jobs_found}")
    lines.append(f"**New jobs this run:** {run.jobs_new}")
    lines.append("")
    lines.append("---")
    lines.append("")

    # ── New UK Jobs ─────────────────────────────────────────────────────
    lines.append("## New UK Jobs")
    lines.append("")
    if new_uk:
        lines.append(f"Found **{len(new_uk)}** new UK posting(s) since last run.")
        lines.append("")
        lines.append("| # | Company | Title | Location | Link |")
        lines.append("|---|---------|-------|----------|------|")
        for i, job in enumerate(new_uk, 1):
            link = f"[Apply]({job.url})" if job.url else "—"
            lines.append(
                f"| {i} | {job.company} | {job.title} | {job.location} | {link} |"
            )
        lines.append("")
    else:
        lines.append("_No new UK jobs found since last run._")
        lines.append("")

    lines.append("---")
    lines.append("")

    # ── Top Matches (UK Only) ───────────────────────────────────────────
    lines.append("## Top Matches (UK Only)")
    lines.append("")
    if top_uk:
        lines.append(f"Found **{len(top_uk)}** UK match(es) with score >= 3.")
        lines.append("")
        lines.append("| # | Company | Title | Location | Score | Link | Match Reason |")
        lines.append("|---|---------|-------|----------|-------|------|--------------|")
        for i, job in enumerate(top_uk, 1):
            link = f"[Apply]({job.url})" if job.url else "—"
            reason = _short_reason(job.score_reasons)
            lines.append(
                f"| {i} | {job.company} | {job.title} | {job.location}"
                f" | {job.score} | {link} | {reason} |"
            )
        lines.append("")
    else:
        lines.append("_No UK jobs matched with score >= 3._")
        lines.append("")

    lines.append("---")
    lines.append("")

    # ── Summary ─────────────────────────────────────────────────────────
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- **Total UK jobs:** {total_uk}")
    lines.append(f"- **New UK jobs:** {len(new_uk)}")
    lines.append(f"- **Top UK matches (score >= 3):** {len(top_uk)}")
    lines.append(f"- **Unknown ATS companies:** {len(unknown_companies)}")
    lines.append("")

    # ── Footer ──────────────────────────────────────────────────────────
    lines.append("---")
    lines.append("_Generated by job-aggregator v1.1_")

    report = "\n".join(lines)
    output_path.write_text(report, encoding="utf-8")
    logger.info("Report written to %s (%d lines)", output_path, len(lines))
    return report


def write_unknown_csv(
    unknown_companies: list[dict],
    output_path: str | Path,
) -> None:
    """
    Write a CSV of companies whose ATS could not be detected.

    Each row includes:
        company, careers_url, detected_links, notes
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    fieldnames = ["company", "careers_url", "detected_links", "notes"]
    with open(output_path, "w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        for c in unknown_companies:
            links = c.get("_detected_links", [])
            writer.writerow({
                "company": c.get("company", ""),
                "careers_url": c.get("careers_url", ""),
                "detected_links": " | ".join(links) if links else "",
                "notes": c.get("notes", ""),
            })

    logger.info("Unknown companies CSV written to %s (%d rows)", output_path, len(unknown_companies))


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _short_reason(reasons: list[str]) -> str:
    """Collapse score_reasons into a compact string for the table."""
    if not reasons:
        return "—"
    # Take at most 3 reasons, shorten each
    short = []
    for r in reasons[:3]:
        # Strip the score prefix like "+3 " or "-5 "
        cleaned = r.split(" ", 1)[-1] if " " in r else r
        short.append(cleaned)
    suffix = f" (+{len(reasons) - 3} more)" if len(reasons) > 3 else ""
    return "; ".join(short) + suffix
