"""
Markdown report generator + unknown-companies CSV export.

Report structure (v1.1):
  1. Header + run summary
  2. New UK Jobs (first_seen > last run AND is_uk_role)
  3. Top Matches — UK Only (score >= 3 AND is_uk_role)
  4. Summary counts
"""

from __future__ import annotations

import csv
import logging
from pathlib import Path

from src.core.models import Job, RunRecord
from src.core.utils import is_uk_role

logger = logging.getLogger(__name__)


def generate_report(
    *,
    run: RunRecord,
    new_jobs: list[Job],
    all_jobs: list[Job],
    unknown_companies: list[dict],
    output_path: str | Path,
) -> str:
    """
    Generate a Markdown report and write it to *output_path*.

    Args:
        new_jobs: Jobs whose first_seen > previous run time (already scored).
        all_jobs: Every job fetched this run (already scored).
        unknown_companies: Company rows where ATS was not resolved.
        output_path: Where to write report.md.

    Returns the report content as a string.
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # ── Filter to UK ────────────────────────────────────────────────────
    new_uk = [j for j in new_jobs if is_uk_role(j.location)]
    new_uk.sort(key=lambda j: (j.company, j.title))

    top_uk = sorted(
        [j for j in all_jobs if j.score >= 3 and is_uk_role(j.location)],
        key=lambda j: j.score,
        reverse=True,
    )

    total_uk = sum(1 for j in all_jobs if is_uk_role(j.location))

    lines: list[str] = []

    # ── Header ──────────────────────────────────────────────────────────
    lines.append("# Job Aggregation Report")
    lines.append("")
    lines.append(f"**Run ID:** `{run.run_id}`")
    lines.append(f"**Timestamp:** {run.run_time}")
    lines.append(f"**Companies processed:** {run.companies_processed}")
    lines.append(f"**Total jobs found:** {run.jobs_found}")
    lines.append(f"**New jobs this run:** {run.jobs_new}")
    lines.append("")
    lines.append("---")
    lines.append("")

    # ── New UK Jobs ─────────────────────────────────────────────────────
    lines.append("## New UK Jobs")
    lines.append("")
    if new_uk:
        lines.append(f"Found **{len(new_uk)}** new UK posting(s) since last run.")
        lines.append("")
        lines.append("| # | Company | Title | Location | Link |")
        lines.append("|---|---------|-------|----------|------|")
        for i, job in enumerate(new_uk, 1):
            link = f"[Apply]({job.url})" if job.url else "—"
            lines.append(
                f"| {i} | {job.company} | {job.title} | {job.location} | {link} |"
            )
        lines.append("")
    else:
        lines.append("_No new UK jobs found since last run._")
        lines.append("")

    lines.append("---")
    lines.append("")

    # ── Top Matches (UK Only) ───────────────────────────────────────────
    lines.append("## Top Matches (UK Only)")
    lines.append("")
    if top_uk:
        lines.append(f"Found **{len(top_uk)}** UK match(es) with score >= 3.")
        lines.append("")
        lines.append("| # | Company | Title | Location | Score | Link | Match Reason |")
        lines.append("|---|---------|-------|----------|-------|------|--------------|")
        for i, job in enumerate(top_uk, 1):
            link = f"[Apply]({job.url})" if job.url else "—"
            reason = _short_reason(job.score_reasons)
            lines.append(
                f"| {i} | {job.company} | {job.title} | {job.location}"
                f" | {job.score} | {link} | {reason} |"
            )
        lines.append("")
    else:
        lines.append("_No UK jobs matched with score >= 3._")
        lines.append("")

    lines.append("---")
    lines.append("")

    # ── Summary ─────────────────────────────────────────────────────────
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- **Total UK jobs:** {total_uk}")
    lines.append(f"- **New UK jobs:** {len(new_uk)}")
    lines.append(f"- **Top UK matches (score >= 3):** {len(top_uk)}")
    lines.append(f"- **Unknown ATS companies:** {len(unknown_companies)}")
    lines.append("")

    # ── Footer ──────────────────────────────────────────────────────────
    lines.append("---")
    lines.append("_Generated by job-aggregator v1.1_")

    report = "\n".join(lines)
    output_path.write_text(report, encoding="utf-8")
    logger.info("Report written to %s (%d lines)", output_path, len(lines))
    return report


def write_diff_report(
    *,
    run: RunRecord,
    new_jobs: list[Job],
    previous_run_time: str | None,
    output_path: str | Path,
    limit_top: int = 25,
    limit_uk: int = 40,
    limit_other: int = 25,
    min_score: int = 3,
) -> str:
    """
    Generate a diff report showing what changed since the previous run.

    Sections (only if non-empty):
      1. Header + run context
      2. Top New Matches (score >= min_score, capped at limit_top)
      3. New UK Jobs (capped at limit_uk, excluding top matches)
      4. Other New Jobs (capped at limit_other)
      5. Summary counts

    Returns the report content as a string.
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = []

    # ── Header (always shown) ────────────────────────────────────────────
    lines.append("# Diff Report")
    lines.append("")
    lines.append(f"**Run ID:** `{run.run_id}`")
    lines.append(f"**Timestamp:** {run.run_time}")
    if previous_run_time:
        lines.append(f"**Previous run:** {previous_run_time}")
    else:
        lines.append("**Previous run:** _No previous run found (first run)_")
    lines.append(f"**New jobs this run:** {len(new_jobs)}")
    lines.append("")

    # ── Early return when nothing new ────────────────────────────────────
    if not new_jobs:
        lines.append("No new jobs since last run.")
        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append("## Summary")
        lines.append("")
        lines.append("- **Total new jobs:** 0")
        lines.append("- **Top matches (score ≥ 3):** 0")
        lines.append("- **New UK jobs (other):** 0")
        lines.append("- **Other new jobs:** 0")
        lines.append("")
        lines.append("---")
        lines.append("_Generated by job-aggregator diff mode_")
        report = "\n".join(lines)
        output_path.write_text(report, encoding="utf-8")
        logger.info("Diff report written to %s (%d lines, no new jobs)", output_path, len(lines))
        return report

    # ── Categorise new jobs ──────────────────────────────────────────────
    top_new_all = sorted(
        [j for j in new_jobs if j.score >= min_score],
        key=lambda j: j.score,
        reverse=True,
    )
    top_new_urls = {j.url for j in top_new_all}

    new_uk_all = sorted(
        [j for j in new_jobs if is_uk_role(j.location) and j.url not in top_new_urls],
        key=lambda j: (j.company, j.title),
    )
    new_uk_urls = {j.url for j in new_uk_all}

    other_new_all = sorted(
        [j for j in new_jobs if j.url not in top_new_urls and j.url not in new_uk_urls],
        key=lambda j: (j.company, j.title),
    )

    # Apply caps
    top_new = top_new_all[:limit_top]
    new_uk = new_uk_all[:limit_uk]
    other_new = other_new_all[:limit_other]

    lines.append("---")
    lines.append("")

    # ── Top New Matches ─────────────────────────────────────────────────
    if top_new_all:
        lines.append(f"## Top New Matches (score ≥ {min_score})")
        lines.append("")
        lines.append(f"Found **{len(top_new_all)}** new high-scoring job(s).")
        lines.append("")
        lines.append("| # | Company | Title | Location | Score | Link | Match Reason |")
        lines.append("|---|---------|-------|----------|-------|------|--------------|")
        for i, job in enumerate(top_new, 1):
            link = f"[Apply]({job.url})" if job.url else "—"
            reason = _short_reason(job.score_reasons)
            uk_tag = " 🇬🇧" if is_uk_role(job.location) else ""
            lines.append(
                f"| {i} | {job.company} | {job.title} | {job.location}{uk_tag}"
                f" | {job.score} | {link} | {reason} |"
            )
        if len(top_new_all) > limit_top:
            lines.append(f"\n... and {len(top_new_all) - limit_top} more not shown")
        lines.append("")
        lines.append("---")
        lines.append("")

    # ── New UK Jobs ─────────────────────────────────────────────────────
    if new_uk_all:
        lines.append("## New UK Jobs")
        lines.append("")
        lines.append(f"Found **{len(new_uk_all)}** new UK posting(s) not in top matches.")
        lines.append("")
        lines.append("| # | Company | Title | Location | Score | Link |")
        lines.append("|---|---------|-------|----------|-------|------|")
        for i, job in enumerate(new_uk, 1):
            link = f"[Apply]({job.url})" if job.url else "—"
            lines.append(
                f"| {i} | {job.company} | {job.title} | {job.location}"
                f" | {job.score} | {link} |"
            )
        if len(new_uk_all) > limit_uk:
            lines.append(f"\n... and {len(new_uk_all) - limit_uk} more not shown")
        lines.append("")
        lines.append("---")
        lines.append("")

    # ── Other New Jobs ──────────────────────────────────────────────────
    if other_new_all:
        lines.append("## Other New Jobs")
        lines.append("")
        lines.append(f"Found **{len(other_new_all)}** other new posting(s).")
        lines.append("")
        lines.append("| # | Company | Title | Location | Score | Link |")
        lines.append("|---|---------|-------|----------|-------|------|")
        for i, job in enumerate(other_new, 1):
            link = f"[Apply]({job.url})" if job.url else "—"
            lines.append(
                f"| {i} | {job.company} | {job.title} | {job.location}"
                f" | {job.score} | {link} |"
            )
        if len(other_new_all) > limit_other:
            lines.append(f"\n... and {len(other_new_all) - limit_other} more not shown")
        lines.append("")
        lines.append("---")
        lines.append("")

    # ── Summary ─────────────────────────────────────────────────────────
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- **Total new jobs:** {len(new_jobs)}")
    lines.append(f"- **Top matches (score ≥ {min_score}):** {len(top_new_all)}")
    top_new_uk_count = sum(1 for j in top_new_all if is_uk_role(j.location))
    lines.append(f"  - of which UK: {top_new_uk_count}")
    lines.append(f"- **New UK jobs (other):** {len(new_uk_all)}")
    lines.append(f"- **Other new jobs:** {len(other_new_all)}")
    lines.append("")
    lines.append("---")
    lines.append("_Generated by job-aggregator diff mode_")

    report = "\n".join(lines)
    output_path.write_text(report, encoding="utf-8")
    logger.info("Diff report written to %s (%d lines)", output_path, len(lines))
    return report


def write_unknown_csv(
    unknown_companies: list[dict],
    output_path: str | Path,
) -> None:
    """
    Write a CSV of companies whose ATS could not be detected.

    Each row includes:
        company, careers_url, detected_links, notes
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    fieldnames = ["company", "careers_url", "detected_links", "notes"]
    with open(output_path, "w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        for c in unknown_companies:
            links = c.get("_detected_links", [])
            writer.writerow({
                "company": c.get("company", ""),
                "careers_url": c.get("careers_url", ""),
                "detected_links": " | ".join(links) if links else "",
                "notes": c.get("notes", ""),
            })

    logger.info("Unknown companies CSV written to %s (%d rows)", output_path, len(unknown_companies))


# ---------------------------------------------------------------------------
# Shortlist outputs
# ---------------------------------------------------------------------------

def write_shortlist_md(
    *,
    jobs: list[Job],
    output_path: str | Path,
    run_id: str,
    generated_at: str,
    limit: int,
    uk_only: bool,
    exclude_seniority: list[str],
    intent_enabled: bool = False,
) -> None:
    """Write a Markdown shortlist of the top *limit* jobs."""
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = []
    lines.append("# Shortlist")
    lines.append("")
    lines.append(f"**Run ID:** `{run_id}`")
    lines.append(f"**Generated:** {generated_at}")
    lines.append(f"**Top N:** {limit}")
    lines.append(f"**UK only:** {uk_only}")
    if exclude_seniority:
        lines.append(f"**Excluded seniority:** {', '.join(exclude_seniority)}")
    lines.append(f"**Intent scoring:** {'enabled' if intent_enabled else 'off'}")
    lines.append(f"**Results:** {len(jobs)}")
    lines.append("")

    if not jobs:
        lines.append("_No jobs matched the shortlist criteria._")
    else:
        # Group by tag in priority order
        from src.core.taxonomy import TAG_PRIORITY, DEFAULT_TAG
        tag_order = TAG_PRIORITY + [DEFAULT_TAG]
        grouped: dict[str, list[tuple[int, Job]]] = {}
        for i, job in enumerate(jobs, 1):
            grouped.setdefault(job.tag, []).append((i, job))

        for tag in tag_order:
            items = grouped.get(tag)
            if not items:
                continue
            lines.append(f"### {tag} ({len(items)})")
            lines.append("")
            if intent_enabled:
                lines.append("| # | Company | Title | Location | Age | Score | Base | Δ | Link | Reason |")
                lines.append("|---|---------|-------|----------|-----|-------|------|---|------|--------|")
                for rank, job in items:
                    link = f"[Apply]({job.url})" if job.url else "—"
                    reason = _short_reason(job.score_reasons)
                    if job.recency_reason:
                        reason += f"; {job.recency_reason}"
                    d = job.intent_delta + job.recency_delta
                    d_str = f"+{d}" if d > 0 else str(d) if d else "0"
                    age_str = f"{job.age_days}d" if job.age_days is not None else "-"
                    lines.append(
                        f"| {rank} | {job.company} | {job.title} | {job.location}"
                        f" | {age_str} | {job.final_score} | {job.score} | {d_str} | {link} | {reason} |"
                    )
            else:
                lines.append("| # | Company | Title | Location | Age | Score | Link | Reason |")
                lines.append("|---|---------|-------|----------|-----|-------|------|--------|")
                for rank, job in items:
                    link = f"[Apply]({job.url})" if job.url else "—"
                    reason = _short_reason(job.score_reasons)
                    if job.recency_reason:
                        reason += f"; {job.recency_reason}"
                    age_str = f"{job.age_days}d" if job.age_days is not None else "-"
                    lines.append(
                        f"| {rank} | {job.company} | {job.title} | {job.location}"
                        f" | {age_str} | {job.score} | {link} | {reason} |"
                    )
            lines.append("")

    lines.append("---")
    lines.append("_Generated by job-aggregator shortlist_")

    output_path.write_text("\n".join(lines), encoding="utf-8")
    logger.info("Shortlist MD written to %s (%d jobs)", output_path, len(jobs))


def write_shortlist_csv(
    *,
    jobs: list[Job],
    output_path: str | Path,
    intent_enabled: bool = False,
) -> None:
    """Write a CSV shortlist for easy filtering."""
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    if intent_enabled:
        fieldnames = [
            "rank", "tag", "company", "title", "location", "age_days",
            "final_score", "base_score", "intent_delta", "recency_delta",
            "url", "match_reason", "intent_reasons", "recency_reason",
        ]
    else:
        fieldnames = [
            "rank", "tag", "company", "title", "location", "age_days",
            "score", "url", "match_reason", "recency_reason",
        ]

    with open(output_path, "w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        for i, job in enumerate(jobs, 1):
            age = job.age_days if job.age_days is not None else ""
            if intent_enabled:
                writer.writerow({
                    "rank": i,
                    "tag": job.tag,
                    "company": job.company,
                    "title": job.title,
                    "location": job.location,
                    "age_days": age,
                    "final_score": job.final_score,
                    "base_score": job.score,
                    "intent_delta": job.intent_delta,
                    "recency_delta": job.recency_delta,
                    "url": job.url or "",
                    "match_reason": "; ".join(job.score_reasons) if job.score_reasons else "",
                    "intent_reasons": "; ".join(job.intent_reasons) if job.intent_reasons else "",
                    "recency_reason": job.recency_reason,
                })
            else:
                writer.writerow({
                    "rank": i,
                    "tag": job.tag,
                    "company": job.company,
                    "title": job.title,
                    "location": job.location,
                    "age_days": age,
                    "score": job.score,
                    "url": job.url or "",
                    "match_reason": "; ".join(job.score_reasons) if job.score_reasons else "",
                    "recency_reason": job.recency_reason,
                })

    logger.info("Shortlist CSV written to %s (%d jobs)", output_path, len(jobs))


# ---------------------------------------------------------------------------
# Brief output
# ---------------------------------------------------------------------------

def write_brief_md(
    *,
    output_path: str | Path,
    run: RunRecord,
    shortlist_jobs: list[Job],
    intent_enabled: bool = False,
    new_uk_count: int = 0,
    unknown_ats_count: int = 0,
) -> None:
    """Write a human-readable brief with compact bullet-style job listings."""
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = []
    lines.append("# Job Brief")
    lines.append("")
    lines.append(f"**Run:** `{run.run_id}` | {run.run_time}")
    lines.append(f"**Companies:** {run.companies_processed} | "
                 f"**Jobs:** {run.jobs_found} | "
                 f"**New:** {run.jobs_new} | "
                 f"**New UK:** {new_uk_count} | "
                 f"**Unknown ATS:** {unknown_ats_count}")
    lines.append("")

    apply_now = shortlist_jobs[:8]
    worth_a_look = shortlist_jobs[8:20]

    def _job_bullet(job: Job) -> list[str]:
        tag_label = f" [{job.tag}]" if job.tag != "OTHER" else ""
        age_str = f" | {job.age_days}d old" if job.age_days is not None else ""
        if intent_enabled:
            d = job.intent_delta + job.recency_delta
            d_str = f"+{d}" if d > 0 else str(d) if d else "0"
            score_str = f"{job.final_score} (base {job.score}, Δ{d_str})"
        else:
            score_str = str(job.score)
        reason = _short_reason(job.score_reasons)
        intent_r = ""
        if intent_enabled and job.intent_reasons:
            intent_r = " | " + _truncate("; ".join(job.intent_reasons), 80)
        recency_r = ""
        if job.recency_reason:
            recency_r = f" | {job.recency_reason}"
        bullet: list[str] = []
        bullet.append(f"- **{job.company} — {job.title}**{tag_label}  Score: {score_str}{age_str}")
        bullet.append(f"  {job.location}")
        bullet.append(f"  Why: {reason}{intent_r}{recency_r}")
        if job.url:
            bullet.append(f"  [Apply]({job.url})")
        return bullet

    if apply_now:
        lines.append("## Apply Now")
        lines.append("")
        for job in apply_now:
            lines.extend(_job_bullet(job))
            lines.append("")

    if worth_a_look:
        lines.append("## Worth a Look")
        lines.append("")
        for job in worth_a_look:
            lines.extend(_job_bullet(job))
            lines.append("")

    if not apply_now and not worth_a_look:
        lines.append("_No shortlisted jobs to show._")
        lines.append("")

    lines.append("---")
    lines.append("_Generated by job-aggregator brief_")

    output_path.write_text("\n".join(lines), encoding="utf-8")
    logger.info("Brief written to %s (%d jobs)", output_path, len(shortlist_jobs))


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _short_reason(reasons: list[str]) -> str:
    """Collapse score_reasons into a compact string for the table."""
    if not reasons:
        return "—"
    # Take at most 3 reasons, shorten each
    short = []
    for r in reasons[:3]:
        # Strip the score prefix like "+3 " or "-5 "
        cleaned = r.split(" ", 1)[-1] if " " in r else r
        short.append(cleaned)
    suffix = f" (+{len(reasons) - 3} more)" if len(reasons) > 3 else ""
    return "; ".join(short) + suffix


def _truncate(text: str, max_len: int) -> str:
    """Truncate text to max_len, adding ellipsis if needed."""
    if len(text) <= max_len:
        return text
    return text[: max_len - 3] + "..."
